# https://taskfile.dev
version: "3"

vars:
    PROJECT_NAME: "ttiler"
    PACKAGE_DIR: "build/package"

tasks:
    watch:
        aliases: [log]
        cmds:
            - journalctl -f -t kwin_wayland_wrapper --grep="js:"

    install:
        deps: [pack]
        cmds:
            - task: set-enable
              vars: { ENABLE: false }
            - task: uninstall
            - "kpackagetool6 -t KWin/Script --install {{.PACKAGE_DIR}}"
            - task: set-enable
              vars: { ENABLE: true }

    uninstall:
        cmds:
            - task: set-enable
              vars: { ENABLE: false }
            - echo "Waiting for kwin to disable the script..."
              && sleep 0.5s
            - echo "Removing shortcuts for disabled kwin scripts..."
              && echo -n " - Did remove any shortcuts..."
              && qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.cleanUp
            - "kpackagetool6 -t KWin/Script --remove {{.PROJECT_NAME}}"
        status:
            # Throw error if already installed, otherwise suppress all errors (any error will cancel the task)
            - "kpackagetool6 -t KWin/Script --show {{.PROJECT_NAME}} && exit 1 || exit 0"

    set-enable:
        label: "set-enable: {{.ENABLE}}"
        internal: true
        run: when_changed
        requires:
            vars:
                - name: ENABLE
                  enum: [true, false]
        cmds:
            - "kwriteconfig6 --file kwinrc --group Plugins --key {{.PROJECT_NAME}}Enabled {{.ENABLE}}"
            - qdbus org.kde.KWin /KWin reconfigure

    package:
        aliases: [pack]
        deps: [build]
        cmds:
            - mkdir -p "{{.PACKAGE_DIR}}/contents/code"
            - cp -f metadata.json "{{.PACKAGE_DIR}}/metadata.json"
            - cp -f build/bundle/bundle.js "{{.PACKAGE_DIR}}/contents/code/main.js"
        sources:
            - metadata.json
            - build/bundle/bundle.js
        generates:
            - "{{.PACKAGE_DIR}}/**/*"

    clean:
        cmds:
            - rm -rvf build

    build:
        deps: [install-deps]
        cmds:
            - cmd: npx tsc
              ignore_error: true
            - npx rollup --config

    install-deps:
        cmds:
            - npm install
        sources:
            - package.json
            - package-lock.json
        generates:
            - node_modules/**/*
