/**
 * Declarations that was not autogenerated in kwin-autogenerated.d.ts
 */

declare namespace KWin {
    interface WorkspaceWrapper {
        slotWindowQuickTileRight(): void
        slotWindowQuickTileLeft(): void
    }
}

declare type QRect = {
    readonly left: number
    readonly top: number
    readonly right: number
    readonly bottom: number

    x: number
    y: number
    width: number
    height: number
}

declare type QRectF = QRect
