/**
 * Declarations that was not autogenerated in kwin-autogenerated.d.ts
 */

declare namespace KWin {
    interface WorkspaceWrapper {
        slotWindowQuickTileRight(): void
        slotWindowQuickTileLeft(): void
    }
}

declare type QRect = {
    left: number
    top: number
    right: number
    bottom: number
}

declare type QRectF = QRect
