/**
 * Declarations that was not autogenerated in kwin-autogenerated.d.ts
 */
declare namespace KWin {
    interface WorkspaceWrapper {
        slotWindowQuickTileRight(): void
        slotWindowQuickTileLeft(): void
    }
}
